# Generated by Django 5.1.7 on 2025-07-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customemail',
            name='sender_email',
            field=models.EmailField(default='admin@limbsorthopaedic.org', max_length=254),
        ),
    ]
