# Generated by Django 5.1.7 on 2025-10-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limbs_cyber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='transaction_number',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
