# Generated by Django 5.1.7 on 2025-10-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limbs_cyber', '0002_alter_sale_transaction_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('M-Pesa', 'M-Pesa (0708581688)'), ('Cash', 'Cash')], default='M-Pesa', max_length=50),
        ),
    ]
