# Generated by Django 5.1.7 on 2025-12-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limbs_cyber', '0003_alter_sale_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('M-Pesa', 'M-Pesa'), ('Cash', 'Cash')], default='M-Pesa', max_length=50),
        ),
    ]
