# Generated by Django 5.1.7 on 2025-06-10 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('other_service', models.CharField(blank=True, help_text='If service not listed above', max_length=200, null=True)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('notes', models.TextField(blank=True, help_text='Any additional information or special requirements', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes for admin purposes only', null=True)),
                ('treatment_notes', models.TextField(blank=True, help_text="Detailed notes about patient's treatment", null=True)),
                ('treatment_date', models.DateField(blank=True, help_text='Date when treatment was provided', null=True)),
                ('follow_up_date', models.DateField(blank=True, help_text='Date for follow-up appointment if needed', null=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, help_text='Doctor assigned to this appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_appointments', to='accounts.doctor')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='services.service')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-preferred_date', '-preferred_time'],
            },
        ),
    ]
