# Generated by Django 5.1.7 on 2025-06-10 00:25

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text="Unique identifier used in templates (e.g., 'home-hero', 'about-intro')", max_length=100, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='page_sections/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL (used if no image is uploaded)', max_length=500, null=True)),
                ('button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('button_url', models.CharField(blank=True, max_length=255, null=True)),
                ('section_type', models.CharField(choices=[('hero', 'Hero Section'), ('content', 'Content Section'), ('feature', 'Feature Section'), ('cta', 'Call to Action'), ('gallery', 'Gallery'), ('testimonial', 'Testimonial'), ('faq', 'FAQ'), ('other', 'Other')], default='content', max_length=20)),
                ('custom_css_class', models.CharField(blank=True, help_text='Additional CSS classes to apply to this section', max_length=100, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Section',
                'verbose_name_plural': 'Page Sections',
                'ordering': ['order', 'identifier'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Unique key used to access this setting (e.g., 'contact_email', 'facebook_url')", max_length=100, unique=True)),
                ('value', models.TextField(default='', help_text='Value of the setting')),
                ('description', models.TextField(blank=True, help_text='Optional description for this setting', null=True)),
                ('is_public', models.BooleanField(default=True, help_text='If unchecked, this setting will not be available in templates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
                'ordering': ['key'],
            },
        ),
    ]
