# Generated by Django 5.1.7 on 2026-01-23 17:15

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LOLProductService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LOL - Products & Services List',
                'verbose_name_plural': 'LOL - Products & Services List',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('age_years', models.PositiveIntegerField(default=0)),
                ('age_months', models.PositiveIntegerField(default=0)),
                ('child_or_adult', models.CharField(choices=[('Child', 'Child'), ('Adult', 'Adult')], max_length=10)),
                ('brought_by', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(max_length=20)),
                ('alt_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('residence', models.CharField(max_length=255)),
                ('info_source', models.CharField(blank=True, max_length=255, null=True, verbose_name='How did you hear about us?')),
                ('unique_code', models.CharField(editable=False, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_status', models.CharField(choices=[('New', 'New'), ('Old', 'Old')], default='New', max_length=10)),
                ('snapshot_full_name', models.CharField(max_length=255)),
                ('snapshot_gender', models.CharField(max_length=10)),
                ('snapshot_age_years', models.PositiveIntegerField(default=0)),
                ('snapshot_age_months', models.PositiveIntegerField(default=0)),
                ('snapshot_child_or_adult', models.CharField(max_length=10)),
                ('snapshot_brought_by', models.CharField(blank=True, max_length=255, null=True)),
                ('snapshot_contact', models.CharField(max_length=20)),
                ('snapshot_alt_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('snapshot_residence', models.CharField(max_length=255)),
                ('snapshot_info_source', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatment_notes', models.TextField(blank=True, null=True)),
                ('next_visit', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='lol_register.patient')),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_time', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('To Make', 'To Make'), ('Made/Fitted', 'Made/Fitted'), ('Repaired', 'Repaired'), ('Cancelled', 'Cancelled')], default='To Make', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lol_register.lolproductservice')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_products', to='lol_register.visit')),
            ],
            options={
                'verbose_name': 'Visit Product',
                'verbose_name_plural': 'Visit Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LOLPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('LOL-MPESA', 'LOL-MPESA'), ('LOL-CASH', 'LOL-CASH')], max_length=20)),
                ('expected_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('mpesa_transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='lol_register.visit')),
                ('visit_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='lol_register.visitproduct')),
            ],
            options={
                'verbose_name': 'LOL Payment',
                'verbose_name_plural': 'LOL Payments (Cash Book)',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('To Make', 'To Make'), ('In Progress', 'In Progress'), ('Made', 'Made'), ('Fitted', 'Fitted'), ('Repaired', 'Repaired')], default='To Make', max_length=20)),
                ('expected_ready_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workshop_orders', to=settings.AUTH_USER_MODEL)),
                ('visit_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_order', to='lol_register.visitproduct')),
            ],
            options={
                'verbose_name': 'Workshop Order',
                'verbose_name_plural': 'Workshop Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
