# Generated by Django 5.1.7 on 2026-03-19 10:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitproduct',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Discount on Product/Service'),
        ),
        migrations.AddField(
            model_name='visitproduct',
            name='tip',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Tip on Product/Service'),
        ),
    ]
