# Generated by Django 5.1.7 on 2026-03-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age_months',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='age_years',
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
