# Generated by Django 5.1.7 on 2025-12-12 13:11

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_register', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lolpayment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'LOL Payment', 'verbose_name_plural': 'LOL Payments (Cash Book)'},
        ),
        migrations.AlterModelOptions(
            name='lolproductservice',
            options={'ordering': ['name'], 'verbose_name': 'LOL - Products & Services List', 'verbose_name_plural': 'LOL - Products & Services List'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at'], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-created_at'], 'verbose_name': 'Visit', 'verbose_name_plural': 'Visits'},
        ),
        migrations.AlterModelOptions(
            name='visitproduct',
            options={'ordering': ['-created_at'], 'verbose_name': 'Visit Product', 'verbose_name_plural': 'Visit Products'},
        ),
        migrations.AlterModelOptions(
            name='workshoporder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Workshop Order', 'verbose_name_plural': 'Workshop Orders'},
        ),
        migrations.AddField(
            model_name='lolpayment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lolpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lolproductservice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lolproductservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='snapshot_alt_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='snapshot_brought_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='snapshot_info_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visitproduct',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workshoporder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workshoporder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lolpayment',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='lolpayment',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='lolpayment',
            name='expected_pay',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lolpayment',
            name='paid_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lolpayment',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='lol_register.visit'),
        ),
        migrations.AlterField(
            model_name='lolpayment',
            name='visit_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='lol_register.visitproduct'),
        ),
        migrations.AlterField(
            model_name='lolproductservice',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='lolproductservice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age_months',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='alt_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='patient',
            name='info_source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='How did you hear about us?'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='unique_code',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='lol_register.patient'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='snapshot_age_months',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visit',
            name='snapshot_age_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visit',
            name='snapshot_child_or_adult',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='visit',
            name='snapshot_contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='visit',
            name='snapshot_full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='snapshot_gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='visit',
            name='snapshot_residence',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_status',
            field=models.CharField(choices=[('New', 'New'), ('Old', 'Old')], default='New', max_length=10),
        ),
        migrations.AlterField(
            model_name='visitproduct',
            name='price_at_time',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='visitproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='visitproduct',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_products', to='lol_register.visit'),
        ),
        migrations.AlterField(
            model_name='workshoporder',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workshop_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
