# Generated by Django 5.1.7 on 2026-04-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_register', '0002_visitproduct_discount_visitproduct_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='doctors_information',
            field=models.CharField(blank=True, choices=[('Attended To', 'Attended To'), ('Committed', 'Committed'), ('Pending', 'Pending'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='doctors_information_others',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Specify Others'),
        ),
        migrations.AddField(
            model_name='visit',
            name='patient_medical_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
