# Generated by Django 5.1.7 on 2026-03-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_register', '0002_remove_patient_age_months_remove_patient_age_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitproduct',
            name='status',
            field=models.CharField(choices=[('To Make', 'To Make'), ('Made/Fitted', 'Made/Fitted'), ('Repaired', 'Repaired'), ('Cancelled', 'Cancelled'), ('Consultation', 'Consultation'), ('Review', 'Review'), ('Therapy', 'Therapy'), ('Plaster Cast', 'Plaster Cast'), ('Fellow OrthoTech', 'Fellow OrthoTech')], default='To Make', max_length=20),
        ),
    ]
