# Generated by Django 5.1.7 on 2025-09-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_add_product_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base price for fixed pricing or fallback price', max_digits=10, null=True),
        ),
    ]
