# Generated by Django 5.1.7 on 2025-10-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty if price varies or is available on request', max_digits=10, null=True),
        ),
    ]
